// <auto-generated />
namespace DbAccess.Migrations.MicroSvrDb
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20181021 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20181021));
        
        string IMigrationMetadata.Id
        {
            get { return "201810211302359_2018.10.21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
